AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions # for Fn::ToJsonString, see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ToJsonString.html
Description: >
  sam-chat-boilerplate

  SAM Template for WebSocket based LLM chat application
  using AWS API Gateway WebSocket API and Lambda.

Parameters:
  WebSocketAPIName:
    Type: String
    Default: SamChatWebSocketAPI
    Description: (Required) The name of the API Gateway WebSocket API.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: app.handler
    Runtime: python3.12
    # the timeout of the API Gateway WebSocket proxy integration is 29s
    # but we use Lambda async invocation for llm related functions
    # so it's safe to set this greater than 29
    Timeout: 300

Resources:
  # websocket api
  WebSocketAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref WebSocketAPIName
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  # TODO: auto re-deploy
  WebSocketAPIDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - LangChainMistralRoute
      - LangChainBedrockRoute
      - LangChainOpenAIRoute
      - BedrockRoute
      - OnConnectRoute
      - OnDefaultRoute
      - OnDisconnectRoute
    Properties:
      ApiId: !Ref WebSocketAPI
  WebSocketAPIProductionStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Production
      DeploymentId: !Ref WebSocketAPIDeployment
      ApiId: !Ref WebSocketAPI

  SessionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: SessionId
        Type: String

  # langchain/bedrock
  LangChainBedrockRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: langchain/bedrock
      AuthorizationType: NONE
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref LangChainBedrockIntegration
  LangChainBedrockIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      IntegrationType: AWS # use non-proxy integration to invoke lambda async
      IntegrationUri:
        # see https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LangChainBedrockFunction.Arn}/invocations
      RequestParameters:
        # see https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-integration-async.html
        &AsyncLambdaIntegrationRequestParameters
        integration.request.header.X-Amz-Invocation-Type: "'Event'"
      RequestTemplates:
        # see https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-mapping-template-reference.html
        &AsyncLambdaIntegrationRequestTemplates
        application/json: !ToJsonString
          requestContext:
            domainName: $context.domainName
            stage: $context.stage
            connectionId: $context.connectionId
          body: $input.body.replaceAll('"', '\"')
  LangChainBedrockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: langchain/bedrock/
      Layers:
        - !Ref LangChainCommonLayer
      Environment:
        Variables:
          SessionTableName: !Ref SessionTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionTable
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*"
            - Effect: Allow
              Action:
                - "bedrock:InvokeModel"
                - "bedrock:InvokeModelWithResponseStream"
              Resource:
                - "arn:aws:bedrock:*::foundation-model/*"
  LangChainBedrockPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketAPI
      - SessionTable
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LangChainBedrockFunction
      Principal: apigateway.amazonaws.com

  # langchain/openai
  LangChainOpenAIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: langchain/openai
      AuthorizationType: NONE
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref LangChainOpenAIIntegration
  LangChainOpenAIIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      IntegrationType: AWS
      IntegrationUri:
        # see https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LangChainOpenAIFunction.Arn}/invocations
      RequestParameters: *AsyncLambdaIntegrationRequestParameters
      RequestTemplates: *AsyncLambdaIntegrationRequestTemplates
  LangChainOpenAIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: langchain/openai/
      Layers:
        - !Ref LangChainCommonLayer
      Environment:
        Variables:
          OpenAI_API_Base: http://neural-chat-q5-114160182.us-west-2.elb.amazonaws.com/v1
          OpenAI_API_Key: "123"
          SessionTableName: !Ref SessionTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionTable
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*"
  LangChainOpenAIPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketAPI
      - SessionTable
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LangChainOpenAIFunction
      Principal: apigateway.amazonaws.com



  # langchain/mistral
  LangChainMistralRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: langchain/mistral
      AuthorizationType: NONE
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref LangChainMistralIntegration
  LangChainMistralIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      IntegrationType: AWS
      IntegrationUri:
        # see https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LangChainMistralFunction.Arn}/invocations
      RequestParameters: *AsyncLambdaIntegrationRequestParameters
      RequestTemplates: *AsyncLambdaIntegrationRequestTemplates
  LangChainMistralFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: langchain/mistral/
      Layers:
        - !Ref LangChainCommonLayer
      Environment:
        Variables:
          Mistral_API_Base: "https://api.mistral.ai/v1/chat/completions"
          Mistral_API_Key: "pv1Rl69upV9DiOVAlBVfhwUCmCJXfVe0"
          Mistral_Model_Name: "mistral-medium"
          SessionTableName: !Ref SessionTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionTable
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*"
  LangChainMistralPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketAPI
      - SessionTable
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LangChainMistralFunction
      Principal: apigateway.amazonaws.com

 

  # bedrock
  BedrockRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: bedrock
      AuthorizationType: NONE
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref BedrockIntegration
  BedrockIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      IntegrationType: AWS
      IntegrationUri:
        # see https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${BedrockFunction.Arn}/invocations
      RequestParameters: *AsyncLambdaIntegrationRequestParameters
      RequestTemplates: *AsyncLambdaIntegrationRequestTemplates
  BedrockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bedrock/
      Environment:
        Variables:
          SessionTableName: !Ref SessionTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionTable
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*"
            - Effect: Allow
              Action:
                - "bedrock:InvokeModel"
                - "bedrock:InvokeModelWithResponseStream"
              Resource:
                - "arn:aws:bedrock:*::foundation-model/*"
  BedrockPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketAPI
      - SessionTable
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BedrockFunction
      Principal: apigateway.amazonaws.com

  # $connect
  OnConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref OnConnectIntegration
  OnConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      IntegrationType: AWS_PROXY
      IntegrationUri:
        # see https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations
  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: connect/
  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com

  # $disconnect
  OnDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref OnDisconnectIntegration
  OnDisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      IntegrationType: AWS_PROXY
      IntegrationUri:
        # see https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations
  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: disconnect/
  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com

  # $default
  OnDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: $default
      AuthorizationType: NONE
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref OnDefaultIntegration
  OnDefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      IntegrationType: AWS_PROXY
      IntegrationUri:
        # see https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDefaultFunction.Arn}/invocations
  OnDefaultRouteResponse:
    Type: AWS::ApiGatewayV2::RouteResponse
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteId: !Ref OnDefaultRoute
      RouteResponseKey: $default
  OnDefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: default/
  OnDefaultPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDefaultFunction
      Principal: apigateway.amazonaws.com

  # lambda layer
  LangChainCommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer/langchain_common/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

Outputs:
  WebSocketAPIEndpoint:
    Value:
      !Join [
        "",
        [
          "wss://",
          !Ref WebSocketAPI,
          ".execute-api.",
          !Ref "AWS::Region",
          ".amazonaws.com/",
          !Ref "WebSocketAPIProductionStage",
        ],
      ]
